#!/bin/sh

zcompinit() {
  setopt extendedglob local_options
  autoload -Uz compinit
  zcd="${ZSH_CACHE_DIR}/zcompdump"
  zcdc="$zcd.zwc"
  compinit -C -d "$zcd"
  # # Compile the completion dump to increase startup speed, if dump is newer or doesn't exist,
  # # in the background as this is doesn't affect the current session
  # { [ ! -f "$zcdc" || "$zcd" -nt "$zcdc" ] && rm -f "$zcdc" && zcompile "$zcd" } &!
}

zcompinit
